name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'

      - name: Flutter pub get
        run: flutter pub get

      - name: Prepare local.properties
        run: |
          echo "flutter.sdk=$FLUTTER_HOME" >> android/local.properties
          echo "flutter.buildMode=release" >> android/local.properties
          echo "flutter.versionName=${GITHUB_RUN_NUMBER:-1}.0.0" >> android/local.properties
          echo "flutter.versionCode=${GITHUB_RUN_NUMBER:-1}" >> android/local.properties

      - name: Make gradlew executable (if present)
        run: |
          if [ -f android/gradlew ]; then chmod +x android/gradlew; fi

      - name: Build APK
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: flutter build apk --release --dart-define=API_BASE_URL=${API_BASE_URL}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk 
